// Repo-level guards: invariants about the project itself rather than about the
// competition. Each of these has bitten a viewer in this family before, so the
// same file lives in every sibling repo.

import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join } from 'node:path'
// Spelled as the LIVE paths on purpose: the frozen-data guard below proves these
// imports do not reach the live modules.
import { GAMES } from '../src/data/schedule.js'
import { PLAYERS } from '../src/data/leaders.js'
import { TEAMS } from '../src/data/teams.js'
import { GAMES_2026 } from './fixtures/season-2026.js'
import { PLAYERS as FROZEN_PLAYERS } from './fixtures/frozen/leaders.js'
import { TEAMS as FROZEN_TEAMS } from './fixtures/frozen/teams.js'

const ROOT = join(import.meta.dirname, '..')
const read = (p) => readFileSync(join(ROOT, p), 'utf8')

function walk(dir) {
  const out = []
  for (const name of readdirSync(join(ROOT, dir))) {
    const rel = `${dir}/${name}`
    if (statSync(join(ROOT, rel)).isDirectory()) out.push(...walk(rel))
    else out.push(rel)
  }
  return out
}

const scripts = walk('scripts').filter((f) => f.endsWith('.mjs'))

describe('scripts runtime', () => {
  it('has scripts to check', () => {
    expect(scripts.length).toBeGreaterThan(0)
  })

  // The data-regeneration scripts run in CI with no `npm install` of app deps.
  // An npm import would work locally and fail in the workflow.
  it('imports only Node built-ins and in-repo source', () => {
    for (const file of scripts) {
      const src = read(file)
      const imports = [...src.matchAll(/^\s*import\s[^'"]*['"]([^'"]+)['"]/gm)].map((m) => m[1])
      for (const spec of imports) {
        const ok = spec.startsWith('node:') || spec.startsWith('./') || spec.startsWith('../')
        expect(ok, `${file} imports "${spec}"`).toBe(true)
      }
    }
  })
})

describe('the ESPN host', () => {
  // site.api.espn.com serves the same routes but 403s from datacenter IPs AND
  // on a browser User-Agent, with no CORS headers. curl with its default UA
  // gets 200, so the host looks healthy from a terminal while every deployed
  // page silently loses live scores. site.web.api serves the same routes.
  it('is site.web.api everywhere it appears', () => {
    const files = [...scripts, 'src/services/espn.js'].filter((f) => existsSync(join(ROOT, f)))
    expect(files).toContain('src/services/espn.js')
    for (const file of files) {
      expect(read(file), file).not.toMatch(/site\.api\.espn\.com\/apis/)
    }
  })
})

describe('the storage namespace', () => {
  // The hub and all the sibling viewers are served from one origin
  // (ismayc.github.io), so localStorage is shared. A key prefix borrowed from a
  // sibling silently reads and writes that app's preferences. Verified against
  // every repo's source on 2026-08-29.
  const FAMILY = [
    ['pl:', 'premier-league'],
    ['nba:', 'the-nba-schedule'],
    ['wnba:', 'the-wnba-schedule'],
    ['nfl:', 'the-nfl-schedule'],
    ['st:', 'hub'],
    ['mmm:', 'the-mens-march-madness'],
    ['mmw:', 'the-womens-march-madness'],
    ['wc2026:', 'world-cup-viewer'],
    ['wwc:', 'womens-world-cup-viewer'],
    ['euros:', 'football-euros-viewer'],
    ['copa:', 'copa-america-viewer'],
    ['fwwc:', 'fiba-womens-world-cup-viewer'],
    ['fmwc:', 'fiba-mens-world-cup-viewer'],
  ]
  const OWN = 'wnba:'
  const files = [...walk('src'), 'index.html'].filter(
    (f) => /\.(js|jsx|html)$/.test(f) && existsSync(join(ROOT, f)),
  )

  it('knows its own prefix is in the family registry', () => {
    expect(FAMILY.map(([p]) => p)).toContain(OWN)
  })

  it('uses this app’s prefix, never a sibling’s', () => {
    for (const file of files) {
      const src = read(file)
      const keys = [...src.matchAll(/localStorage\.(?:get|set|remove)Item\(\s*'([^']+)'/g)].map(
        (m) => m[1],
      )
      for (const key of keys) {
        expect(key.startsWith(OWN), `${file} uses storage key "${key}"`).toBe(true)
      }
    }
  })

  it('never mentions a sibling’s prefix', () => {
    // The leading quote matters: it keeps 'nba:' from matching 'wnba:theme'.
    for (const file of files) {
      const src = read(file)
      for (const [foreign, repo] of FAMILY) {
        if (foreign === OWN) continue
        expect(src.includes(`'${foreign}`), `${file} mentions ${repo}'s "${foreign}"`).toBe(false)
      }
    }
  })
})

describe('generated data', () => {
  // A hand edit to a generated file is silently reverted by the next refresh
  // run, so the banner has to survive.
  it('carries the do-not-edit banner and names its builder', () => {
    for (const file of ['src/data/history.js', 'src/data/leaders.js', 'src/data/schedule.js', 'src/data/teams.js']) {
      const src = read(file)
      expect(src, file).toMatch(/GENERATED by scripts\//)
      expect(src, file).toMatch(/do not edit by hand/)
    }
  })
})

describe('frozen data', () => {
  // The 100% gate must not move when a refresh rewrites src/data. Three times it did
  // (the playoff race on August 10, the week view on September 5, the leaders trade
  // arrow on September 18, 2026), each time because some test still reached a live module,
  // directly or through src/. The frozenData plugin in vite.config.js ends that by
  // resolving every such import to a stand-in. These keep it true.

  // Identity, not equality: the same array object means the import was redirected, not
  // that the live data happens to match today.
  it('is what an import of a live data module actually receives', () => {
    expect(GAMES).toBe(GAMES_2026)
    expect(PLAYERS).toBe(FROZEN_PLAYERS)
    expect(TEAMS).toBe(FROZEN_TEAMS)
  })

  // The shape of the mistake: the fetch script starts writing a fourth module and nobody
  // freezes it, so the suite quietly reads live data again.
  it('covers every module the refresh rewrites', () => {
    const written = [...read('scripts/fetch-schedule.mjs').matchAll(/['"](src\/data\/\w+\.js)['"]/g)]
      .map((m) => m[1])
    expect(written.length).toBeGreaterThan(0)
    const config = read('vite.config.js')
    for (const file of new Set(written)) {
      expect(config, `${file} has no frozen stand-in in vite.config.js`).toContain(`./${file}`)
      expect(existsSync(join(ROOT, file.replace('src/data', 'test/fixtures/frozen'))), file).toBe(true)
    }
  })

  it('keeps the live suite out of the main run, and the main suite out of the live run', () => {
    const config = read('vite.config.js')
    expect(config).toContain("LIVE ? 'test/live/**/*.test.{js,jsx}' : 'test/**/*.test.{js,jsx}'")
    expect(config).toContain("LIVE ? [] : ['test/live/**']")
    expect(JSON.parse(read('package.json')).scripts['test:data']).toBe('LIVE_DATA=1 vitest run')
  })

  // The refresh gate is the live suite. If it drifts back to the coverage gate, a
  // refresh can be blocked by something it did not change.
  it('is not what the refresh workflow gates on', () => {
    const gate = read('.github/workflows/refresh-data.yml').match(/id: gate[\s\S]*?\n\n/)[0]
    expect(gate).toContain('npm run test:data')
    expect(gate).not.toContain('coverage')
  })

  it('never imports a fixture into a live test', () => {
    for (const file of walk('test/live')) {
      if (file.endsWith('parity.test.js')) continue // compares the two on purpose
      expect(read(file), file).not.toMatch(/fixtures\//)
    }
  })
})

describe('the test timezone pin', () => {
  // Every date-derived assertion in this suite reads the pinned zone. A dropped pin
  // fails on a developer's machine in a confusing way and passes on CI, whose runners
  // sit in UTC.
  it('is set to UTC in vite.config.js', () => {
    expect(read('vite.config.js')).toContain("env: { TZ: 'UTC' }")
  })

  it('actually took effect in this process', () => {
    expect(process.env.TZ).toBe('UTC')
  })
})
