// Change detection for the refresh, and the "data as of" stamp it keeps. Node built-ins only.
//
// The footer shows when the committed snapshot last CHANGED (src/data/meta.js), so a
// stalled pipeline shows up on the page. That stamp must move only when the data does.
// The refresh workflow commits, gates, and deploys whenever `git diff -- src/data
// public/logos` is non-empty, so a stamp rewritten on every fetch would turn each of
// the two daily runs into a commit and a deploy with nothing new in it.
//
// So every generated file goes through `writeIfChanged`, which compares the new bytes
// to what is on disk, and the stamp is written the first time any of them differs.
// Stamping on the FIRST change, rather than once at the end of a run, matters for the
// workflow's retry loop: an attempt that writes schedule.js and then dies leaves the
// new schedule on disk, the next attempt finds it unchanged, and a stamp written only
// at the end would never be written at all.

import { readFile, writeFile } from 'node:fs/promises'

// True when `next` (a string or a Buffer) has exactly the bytes of `existing`, the
// file's current content as a Buffer, or null when there is no file yet.
export function sameContent(next, existing) {
  if (existing == null) return false
  return Buffer.from(next).equals(Buffer.from(existing))
}

// Writes `content` to `path` only when it differs from what is there. Returns whether
// it wrote.
export async function writeIfChanged(path, content) {
  let existing = null
  try {
    existing = await readFile(path)
  } catch {
    // No file yet (a first run, or a new logo): anything is a change.
  }
  if (sameContent(content, existing)) return false
  await writeFile(path, content)
  return true
}

export function metaModule(iso) {
  return (
    `// GENERATED by scripts/fetch-schedule.mjs; do not edit by hand.\n` +
    `// When the committed data last changed. Rewritten only when a refresh changes a data\n` +
    `// file or a logo, so its age is the age of the snapshot the site is serving.\n\n` +
    `export const DATA_UPDATED_AT = '${iso}'\n`
  )
}

// One writer per run. `write` is writeIfChanged plus the stamp: the first write that
// changes a file also rewrites `metaPath` with `now()`, once per run.
export function createDataWriter(metaPath, now = () => new Date()) {
  let stampedAt = null
  return {
    async write(path, content) {
      const changed = await writeIfChanged(path, content)
      if (changed && !stampedAt) {
        stampedAt = now().toISOString()
        await writeFile(metaPath, metaModule(stampedAt))
      }
      return changed
    },
    get stampedAt() {
      return stampedAt
    },
  }
}
